name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Cambia esto si tu rama principal no se llama "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Asegúrate de usar una versión compatible con tu proyecto

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Construir el proyecto
      - name: Build the project
        run: npm run build

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Carpeta de salida para React después del build
