name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Cambia a 'main' si tu rama principal se llama así

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Cambia según la versión que uses en tu proyecto

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci # Instalación más eficiente para CI/CD

      # 4. Construir el proyecto
      - name: Build the project
        run: npm run build

      # 5. Desplegar a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Carpeta donde CRA genera los archivos
